# Generated by Django 4.1.6 on 2023-02-11 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=128)),
                ('site_url', models.CharField(max_length=128)),
                ('twitter_url', models.CharField(max_length=128)),
                ('facebook_url', models.CharField(max_length=128)),
                ('linkedin_url', models.CharField(max_length=128)),
                ('youtube_url', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=128)),
                ('is_hidden', models.BooleanField(blank=True, default=False)),
                ('is_hidden_courses', models.BooleanField(blank=True, default=False)),
                ('promotions', models.BooleanField(blank=True, default=False)),
                ('mentor_abs', models.BooleanField(blank=True, default=False)),
                ('email_abs', models.BooleanField(blank=True, default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
