# Generated by Django 4.1.6 on 2023-02-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('sub_title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('Russia', 'Russia'), ('English', 'English'), ('Kyrgyz', 'Kyrgyz'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('French', 'French'), ('Arab', 'Arab'), ('Bengali', 'Bengali'), ('Portuguese', 'Portuguese'), ('German', 'German')], max_length=100)),
                ('level', models.CharField(choices=[('elementary', 'elementary'), ('average', 'average'), ('professional', 'professional'), ('all levels', 'all levels')], max_length=100)),
                ('sub_category', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(default='mentor sphere', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('slides', 'Slides'), ('article', 'Article')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('content', models.TextField(blank=True)),
                ('course_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.courseitem')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='course.theme'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
